/content/documents/socialwork/administration/search-settings:
  jcr:primaryType: hippo:handle
  jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
  hippo:name: Search settings
  /search-settings:
    jcr:primaryType: search:searchsettings
    jcr:mixinTypes: ['mix:referenceable']
    hippo:availability: [live]
    hippostd:retainable: false
    hippostd:state: published
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2026-01-20T09:00:00Z
    hippostdpubwf:lastModificationDate: 2026-01-20T09:00:00Z
    hippostdpubwf:lastModifiedBy: admin
    hippostdpubwf:publicationDate: 2026-01-20T09:00:00Z
    hippostdpubwf:publishedBy: admin
    search:searchtype: resilient
    search:showFilters: false
