definitions:
  config:
    /hst:hst/hst:configurations/rentersrights:
      jcr:primaryType: hst:configuration
      hst:inheritsfrom: [../common]
      /hst:abstractpages:
        jcr:primaryType: hst:pages
      /hst:catalog:
        jcr:primaryType: hst:catalog
      /hst:components:
        jcr:primaryType: hst:components
      /hst:pages:
        jcr:primaryType: hst:pages
      /hst:prototypepages:
        jcr:primaryType: hst:pages
      /hst:sitemap:
        jcr:primaryType: hst:sitemap
        /root:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/homepage
          hst:pagetitle: Home page
          hst:refId: root
          hst:relativecontentpath: ''
      /hst:sitemenus:
        jcr:primaryType: hst:sitemenus
      /hst:templates:
        jcr:primaryType: hst:templates
      /hst:workspace:
        jcr:primaryType: hst:workspace
        jcr:mixinTypes: ['dxphst:mergeable']
        dxphst:treehash: 079CB463F25B876AB388F82494625133
        /hst:channel:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:channel
          hst:name: Renters' rights
          hst:type: website
          hst:channelinfoclass: scot.mygov.publishing.channels.WebsiteInfo
          hst:lastmodifiedby: admin
          hst:defaultdevice: default
          hst:devices: []
          hst:lastmodified: 2025-05-28T11:56:51.291+01:00
        /hst:containers:
          jcr:primaryType: hst:containercomponentfolder
          /homepage:
            jcr:primaryType: hst:containercomponentfolder
            /main:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:containercomponent
              hippo:identifier: c40fc6e0-083e-456c-81f4-b38f4c20e3ce
              hst:label: Home page main
              hst:xtype: hst.vbox
              hst:lastmodified: 2025-05-28T11:59:36.149+01:00
        /hst:pages:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:pages
        /hst:sitemap:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:sitemap
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
          /main:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:sitemenu
            hst:lastmodified: 2021-07-22T14:54:57.725+01:00
