---
sites:
 - id: cloud
   reverse_slash_dns: scot/gov/campaign/cloud
 - id: costofliving
   reverse_slash_dns: scot/gov/campaign/costofliving
 - id: designsystem
   reverse_slash_dns: scot/gov/designsystem
   feedback: true
 - id: digitalconnectivity
   reverse_slash_dns: scot/gov/campaign/digitalconnectivity
 - id: disclosure
   reverse_slash_dns: scot/gov/disclosure/www
 - id: fostercare
   reverse_slash_dns: scot/gov/campaign/fostercare
 - id: rentersrights
   reverse_slash_dns: scot/gov/campaign/rentersrights
 - id: scotaccount
   reverse_slash_dns: scot/gov/campaign/scotaccount
 - id: scotpayments
   reverse_slash_dns: scot/gov/campaign/scotpayments
 - id: servicemanual
   reverse_slash_dns: scot/gov/servicemanual
   feedback: true
 - id: shorttermlets
   reverse_slash_dns: scot/gov/campaign/shorttermlets
 - id: socialsecurity
   feedback: true
   internal: true
   reverse_slash_dns: scot/gov/socialsecurity/www

environments:
  - name: lcl
    gtm: dev
    recaptcha: live
  - name: dev
    gtm: dev
    recaptcha: live
  - name: int
    gtm: dev
    recaptcha: dev
  - name: exp
    gtm: dev
    recaptcha: live
  - name: uat
    gtm: dev
    recaptcha: live
  - name: per
    gtm: dev
    recaptcha: dev
  - name: tst
    gtm: dev
    recaptcha: live
  - name: blu
    gtm: live
    recaptcha: live
  - name: grn
    gtm: live
    recaptcha: live
  - name: live
    gtm: live
    recaptcha: live
