definitions:
  config:
    /hst:hst/hst:configurations/ddat:
      jcr:primaryType: hst:configuration
      hst:inheritsfrom: [../common]
      /hst:abstractpages:
        jcr:primaryType: hst:pages
      /hst:catalog:
        jcr:primaryType: hst:catalog
      /hst:components:
        jcr:primaryType: hst:components
      /hst:pages:
        jcr:primaryType: hst:pages
      /hst:prototypepages:
        jcr:primaryType: hst:pages
      /hst:sitemap:
        jcr:primaryType: hst:sitemap
        /root:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/homepage
          hst:pagetitle: Home page
          hst:refId: root
          hst:relativecontentpath: ''
        /vacancies:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/vacancylist
          hst:pagetitle: List of jobs
          hst:relativecontentpath: /seo/vacancies
          /_any_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/vacancypage
            hst:relativecontentpath: vacancies/${1}
      /hst:sitemenus:
        jcr:primaryType: hst:sitemenus
      /hst:templates:
        jcr:primaryType: hst:templates
        /vacancy:
          jcr:primaryType: hst:template
          hst:renderpath: webfile:/freemarker/ddat/vacancy.ftl
        /vacancylist:
          jcr:primaryType: hst:template
          hst:renderpath: webfile:/freemarker/ddat/vacancylist.ftl
      /hst:workspace:
        jcr:primaryType: hst:workspace
        jcr:mixinTypes: ['dxphst:mergeable']
        dxphst:treehash: 4B349EFC446D1FFEDC5152FAE5CE7E5D
        /hst:channel:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:channel
          hst:name: DDaT
          hst:type: website
          hst:channelinfoclass: scot.mygov.publishing.channels.WebsiteInfo
          hst:lastmodifiedby: admin
          hst:defaultdevice: default
          hst:devices: []
          hst:lastmodified: 2021-07-29T13:31:55.630+01:00
        /hst:containers:
          jcr:primaryType: hst:containercomponentfolder
          /homepage:
            jcr:primaryType: hst:containercomponentfolder
            /main:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:containercomponent
              hippo:identifier: c40fc6e0-083e-456c-81f4-b38f4c20e3ce
              hst:label: Home page main
              hst:xtype: hst.vbox
              hst:lastmodified: 2022-10-31T15:50:06.826Z
          /vacancylist:
            jcr:primaryType: hst:containercomponentfolder
            /main:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:containercomponent
              hippo:identifier: 514d56ef4905403f9c9b5041fefe289f
              hst:label: Vacancy page main
              hst:lastmodified: 2021-07-29T13:32:10.206+01:00
              hst:xtype: hst.vbox
        /hst:pages:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:pages
        /hst:sitemap:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:sitemap
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
          /main:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:sitemenu
            hst:lastmodified: 2021-07-22T14:54:57.725+01:00
