/content/documents/administration/search-settings:
  jcr:primaryType: hippo:handle
  jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
  jcr:uuid: 182a0f10-d049-4dfb-a4d2-d26162c4038e
  hippo:name: Search settings
  hippo:versionHistory: 29b3e2f7-3261-4540-9fa7-f67032e44163
  /search-settings[1]:
    jcr:primaryType: search:searchsettings
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: b0394e1e-a5d8-4018-8a26-3b50892b0315
    hippo:availability: []
    hippostd:retainable: false
    hippostd:state: draft
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2024-03-20T21:23:53.019Z
    hippostdpubwf:lastModificationDate: 2025-08-21T13:07:49.541+01:00
    hippostdpubwf:lastModifiedBy: admin
    search:bloomreachErrorRate: 0.0
    search:enabled: true
    search:funnelbackErrorRate: 0.0
    search:searchtype: resilient
    search:suggestTimeoutMillis: 250
    search:timeoutMillis: 500
  /search-settings[2]:
    jcr:primaryType: search:searchsettings
    jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
    jcr:uuid: 9f3023d4-4ecc-4112-ac07-e7c66f69d9b8
    hippo:availability: [preview]
    hippostd:retainable: false
    hippostd:state: unpublished
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2024-03-20T21:23:53.019Z
    hippostdpubwf:lastModificationDate: 2025-08-19T15:14:37.048+01:00
    hippostdpubwf:lastModifiedBy: admin
    search:bloomreachErrorRate: 0.0
    search:enabled: true
    search:funnelbackErrorRate: 0.0
    search:searchtype: resilient
    search:suggestTimeoutMillis: 250
    search:timeoutMillis: 500
  /search-settings[3]:
    jcr:primaryType: search:searchsettings
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: 213c89da-9bfe-42e7-aea3-080ac6f93d38
    hippo:availability: [live]
    hippostd:retainable: false
    hippostd:state: published
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2024-03-20T21:23:53.019Z
    hippostdpubwf:lastModificationDate: 2025-08-19T15:14:37.048+01:00
    hippostdpubwf:lastModifiedBy: admin
    hippostdpubwf:publicationDate: 2025-08-19T15:14:40.451+01:00
    hippostdpubwf:publishedBy: admin
    search:bloomreachErrorRate: 0.0
    search:enabled: true
    search:funnelbackErrorRate: 0.0
    search:searchtype: resilient
    search:suggestTimeoutMillis: 250
    search:timeoutMillis: 500
