definitions:
  config:
    /hst:hst/hst:configurations/disclosure:
      jcr:primaryType: hst:configuration
      hst:inheritsfrom: [../campaign]
      /hst:workspace:
        jcr:primaryType: hst:workspace
        jcr:mixinTypes: ['dxphst:mergeable']
        dxphst:treehash: 22C4C720AEC4338BA49BCB1BA96D173C
        /hst:channel:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:channel
          hst:name: Disclosure Scotland
          hst:type: website
          hst:channelinfoclass: scot.mygov.publishing.channels.WebsiteInfo
          hst:lastmodifiedby: admin
          hst:defaultdevice: default
          hst:devices: []
          hst:lastmodified: 2024-01-12T09:00:00.000+00:00
        /hst:containers:
          jcr:primaryType: hst:containercomponentfolder
          /homepage:
            jcr:primaryType: hst:containercomponentfolder
            /main:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:containercomponent
              hippo:identifier: c40fc6e0-083e-456c-81f4-b38f4c20e3ce
              hst:label: Home page main
              hst:xtype: hst.vbox
              hst:lastmodified: 2024-01-12T09:00:00.000+00:00
        /hst:pages:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:pages
        /hst:sitemap:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:sitemap
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
          /main:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:sitemenu
            hst:lastmodified: 2024-01-12T09:00:00.000+00:00
