definitions:
  config:
    /hst:hst/hst:configurations/scotaccount:
      jcr:primaryType: hst:configuration
      hst:inheritsfrom: [../campaign]
      /hst:workspace:
        jcr:primaryType: hst:workspace
        jcr:mixinTypes: ['dxphst:mergeable']
        dxphst:treehash: 67BC846C7A39D0B51CAF4E5D87CB228C
        /hst:channel:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:channel
          hst:name: ScotAccount
          hst:type: website
          hst:channelinfoclass: scot.mygov.publishing.channels.WebsiteInfo
          hst:lastmodifiedby: admin
          hst:defaultdevice: default
          hst:devices: []
          hst:lastmodified: 2025-05-28T11:57:31.848+01:00
        /hst:containers:
          jcr:primaryType: hst:containercomponentfolder
          /homepage:
            jcr:primaryType: hst:containercomponentfolder
            /main:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:containercomponent
              hippo:identifier: c40fc6e0-083e-456c-81f4-b38f4c20e3ce
              hst:label: Home page main
              hst:xtype: hst.vbox
              hst:lastmodified: 2023-07-25T09:00:00+01:00
        /hst:sitemap:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:sitemap
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
          /main:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:sitemenu
            hst:lastmodified: 2023-07-25T09:00:00+01:00
